### ISSUE TITLE
[Feat]: model.carrierAccount

### ISSUE THREAD

**Issue by Olijve-CV** [EasyPost/easypost-java#145]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

easy-api-client V5.4.0 
attributes of (type and bill)  not in carrierAccount model which i both need

**Comment by nwithan8** [comment]
We have added `billingType` to the `CarrierAccount` model just recently. It will be available in the next version release.

**Comment by Olijve-CV** [comment]
when is the next version to release

**Comment by nwithan8** [comment]
We do not have an ETA currently.
