### ISSUE TITLE
ClassCastException : gson.internal.LinkedTreeMap cannot be cast to CarrierAccount 

### ISSUE THREAD

**Issue by rajsid1** [EasyPost/easypost-java#16]
https://github.com/EasyPost/easypost-java/blob/master/src/main/java/com/easypost/model/CarrierAccount.java#L90

When trying to get the elements of the list, it is not of type CarrierAccount.
To fix this, check - http://stackoverflow.com/questions/5554217/google-gson-deserialize-listclass-object-generic-type

This is how I fixed it:

```
    public static List<CarrierAccount> all(Map<String, Object> params, String apiKey) throws EasyPostException {
        CarrierAccount[] response = request(RequestMethod.GET, classURL(CarrierAccount.class), params, CarrierAccount[].class, apiKey);
        return Arrays.asList(response);
    }
```

**Comment by pillsilly** [comment]
got ya,you finally have my problem resolved...

thank you so much!

**Comment by att14** [comment]
If you throw your change into a pull request we'll pull it in.

**Comment by rajsid1** [comment]
@att14 seems I don't have access to the repository.

`Permission to EasyPost/easypost-java.git denied to rajsid1.`

**Comment by att14** [comment]
You need to fork the repo, make your changes, and then submit a pull request. https://help.github.com/articles/using-pull-requests/

**Comment by jugaadi** [comment]
@att14  https://github.com/EasyPost/easypost-java/pull/22
