### ISSUE TITLE
Shipment select rate should update remote object

### ISSUE THREAD

**Issue by glapa** [EasyPost/easypost-java#24]
Current version of method `Shipment.setSelectedRate` populates only local object's field. If shipment is handled through batch it's impossible to successful process `Batch.buy` if selected rate were updated after batch creation.

Example code:

     for (com.easypost.model.Shipment shipment: batch.getShipments()) {
         if (ShipmentStatus.valueOf(shipment.getBatchStatus().toUpperCase()) == ShipmentStatus.CREATED) {
             shipment = shipment.refresh();
             shipment = shipment.newRates();
             try {
                 shipment.setSelectedRate(shipment.lowestRate());
             } catch(EasyPostException e) {
             }
         }
     }

     switch (batch.getState()) {
        case "created":
            if (batch.status.getCreated() == batch.getShipments().size()) {
                batch.buy();
            } else {
                 throw new RuntimeException("Batch created but some of shipments failed");
            }
             break;
   
            case "creation_failed":
            case "purchase_failed":
                throw new RuntimeException(String.format("Batch operation failed with status: %s", batch.getState()));
                break;
        }`

**Comment by att14** [comment]
This method should not exist. It is impossible for a user to set selectedRate. It gets set server side upon purchase. I will remove it.

**Comment by glapa** [comment]
Will it always select lowest rate for carrier assigned to shipment?

**Comment by att14** [comment]
No, you have to choose the rate when creating the batch.

https://github.com/EasyPost/easypost-java/blob/master/src/test/java/com/easypost/EasyPostTest.java#L431

Specifically lines 437/438.

**Comment by glapa** [comment]
Does specific available for all addresses that specific carrier can be selected for?

**Comment by att14** [comment]
It depends on what you are trying to do. If you are purchasing a `Shipment` directly you can use the `shipment.lowestRate` method. If you are purchasing `Shipment`s through a batch you need to specify the service level during creation meaning there will will be no guarantee that that service level will be the lowest price.
