### ISSUE TITLE
Missing shipment_id for selected rate

### ISSUE THREAD

**Issue by glapa** [EasyPost/easypost-java#25]
Many of shipments in  batch fails during refreshing (`shipment = shipment.refresh()`).
It's because for some of them `shipment_id` field of selected rate is null. 

**Shipment string received from server**

    {
      ...
      "rates": [
        {
          "id": "******",
          "object": "Rate",
          "created_at": "2016-06-30T22:56:52Z",
          "updated_at": "2016-06-30T22:56:52Z",
          "mode": "production",
          "service": "OnTracGround",
          "carrier": "OnTrac",
          "rate": "6.12",
          "currency": "USD",
          "retail_rate": null,
          "retail_currency": null,
          "list_rate": null,
          "list_currency": null,
          "delivery_days": 1,
          "delivery_date": "2016-07-01T00:00:00Z",
          "delivery_date_guaranteed": null,
          "est_delivery_days": 1,
          "shipment_id": "******",
          "carrier_account_id": "******"
        },
        {
          "id": "******",
          "object": "Rate",
          "created_at": "2016-06-30T22:56:53Z",
          "updated_at": "2016-06-30T22:56:53Z",
          "mode": "production",
          "service": "Gold",
          "carrier": "OnTrac",
          "rate": "81.09",
          "currency": "USD",
          "retail_rate": null,
          "retail_currency": null,
          "list_rate": null,
          "list_currency": null,
          "delivery_days": 1,
          "delivery_date": "2016-07-01T00:00:00Z",
          "delivery_date_guaranteed": null,
          "est_delivery_days": 1,
          "shipment_id": "******",
          "carrier_account_id": "******"
        },
        {
          "id": "******",
          "object": "Rate",
          "created_at": "2016-06-30T22:56:53Z",
          "updated_at": "2016-06-30T22:56:53Z",
          "mode": "production",
          "service": "Sunrise",
          "carrier": "OnTrac",
          "rate": "58.00",
          "currency": "USD",
          "retail_rate": null,
          "retail_currency": null,
          "list_rate": null,
          "list_currency": null,
          "delivery_days": 1,
          "delivery_date": "2016-07-01T00:00:00Z",
          "delivery_date_guaranteed": null,
          "est_delivery_days": 1,
          "shipment_id": "******",
          "carrier_account_id": "******"
        }
      ],
      "refund_status": null,
      "scan_form": null,
      "selected_rate": {
        "id": "******",
        "object": "Rate",
        "created_at": "2016-06-30T22:56:48Z",
        "updated_at": "2016-06-30T22:56:48Z",
        "mode": "production",
        "service": "OnTracGround",
        "carrier": "OnTrac",
        "rate": "6.12",
        "currency": "USD",
        "retail_rate": null,
        "retail_currency": null,
        "list_rate": null,
        "list_currency": null,
        "delivery_days": 1,
        "delivery_date": "2016-07-01T00:00:00Z",
        "delivery_date_guaranteed": null,
        "est_delivery_days": 1,
        "shipment_id": null,
        "carrier_account_id": "******"
      },
      ...
      "id": "******",
      "object": "Shipment"
    }

**Rate Json object passed to Deserializer class**

    {
      "id": "******",
      "object": "Rate",
     "created_at": "2016-06-30T22:56:48Z",
      "updated_at": "2016-06-30T22:56:48Z",
      "mode": "production",
      "service": "OnTracGround",
      "carrier": "OnTrac",
      "rate": "6.12",
      "currency": "USD",
      "retail_rate": null,
      "retail_currency": null,
      "list_rate": null,
      "list_currency": null,
      "delivery_days": 1,
      "delivery_date": "2016-07-01T00:00:00Z",
      "delivery_date_guaranteed": null,
      "est_delivery_days": 1,
      "shipment_id": null,
      "carrier_account_id": "******"
    }

Exception is being thrown in line 88 of `RateDeserializer.java`

(Valid values replaced with `******` for security reasons)

**Comment by victoryftw** [comment]
Thanks for pointing this out. I've just released a new version that should address the cases where the shipment_id is null
