### ISSUE TITLE
[Bug]: Cannot create new tracker for test numbers

### ISSUE THREAD

**Issue by yasnmert** [EasyPost/easypost-java#250]
### Software Version

6.3.1

### Language Version

17

### Operating System

Macos

### What happened?

As stated in the document, real tracker numbers are created only once. 

`Trackers based on tracking_code and carrier; duplicate requests by the same User will simply return the original Tracker.
`

But this rule was not valid for test numbers until about 1 month ago. We could create as many trackers as we wanted with the test number. Currently, we can create a test tracker only once, like a real tracker. Could you check this?

### What was expected?

We want to create a new tracker for the test number every time.

**Comment by nwithan8** [comment]
Hello, thanks for reaching out!

We are currently investigating this internally. However, this is not due to the client library, but rather the API, so wouldn't require any change to this Java library.

We'll keep you updated on the situation.
