### ISSUE TITLE
[Feat]: Adding Secured Funds to Fedex COD API Endpoint

### ISSUE THREAD

**Issue by Riz0** [EasyPost/easypost-java#258]
### Feature Request Is New

- [X] I have verified that the requested feature does not already exist or has not already been requested.

### Description of the feature

Hi guys,

Is there any chance to add the option to allow for secured and guaranteed funds to be enabled with Fedex when using COD on shipping label creation?  Easypost API for FedEx currently  only supports the "CASH", "CHECK", and "MONEY_ORDER" options for cod_method, and none of these options show as "Secured" on the resulting FedEx label.

I requested the respective API docs from my Fedex contact in hopes that it could be helpful to the devs in implementation of that feature. Ground COD has three options:
                                                              
Any payment Type                                                                      
Guaranteed Funds                                                                      
Currency                

Whereas  Express COD has two options:

Secured
Unsecured

I have attached some of the page I found in the developer settings:

FedEx Web Services

https://www.fedex.com/en-us/developer/web-services.html

FedEx Developer Portal (SOAP/REST)

https://developer.fedex.com/api/en-ca/home.html

Image Reference: 

https://support.easypost.com/attachments/token/nlYkPSjzjs0Vk0coHetEf47xW/?name=fedex_securedfunds.png

Just a brief explanation of its purpose from the Fedex site:

"If the shipper marks secured payment on the c.o.d. airbill, we will collect
a cashier’s check, official check or money order. If the shipper marks an unsecured
payment, we will collect a personal check, certified check, cashier’s check, official
check, money order or company check. Cash, traveler’s checks, “com” checks,
credit cards and counter checks will not be accepted in payment of any
c.o.d. amount. "

Can anyone please tell me if there if such an endpoint in easypost or if it will get enabled in the near future? Allowing only unsecured payments is incredibly problematic as it allows for the eventuality of bounced personal checks.  Thanks again

**Comment by nwithan8** [comment]
Hello! Thanks for reaching out!

This isn't something that would need to be added to the  client libraries, but would require an update to our API in general. We have forwarded this information to the proper channels and we'll let you know of any updates!

**Comment by Riz0** [comment]
Hello, 

Thanks for letting me know. I'm guessing there is no public repo where I can follow for such updates to the easypost API? Hoping I can know when it gets implemented so I can start using it immediately. Thanks again
