### ISSUE TITLE
Why i get only USPS rates?

### ISSUE THREAD

**Issue by kanbekotori** [EasyPost/easypost-java#39]
I have add DHL Express in "Carrier Accounts", why i still get USPS rates only.
https://www.easypost.com/getting-started/java.html#step3

```
USPS (Express) - 33.759998
USPS (First) - 3.460000
USPS (Priority) - 7.040000
USPS (ParcelSelect) - 7.200000
```

Run with test key and production key.

**Comment by geddes** [comment]
Hi there - 

The answer likely depends on some of your account details. For confidentiality reasons, please send an e-mail to support@easypost.com with your carrier_account_id for the DHL Express carrier account. We'll be able to look into it there. 

Thanks,
 Geddes
