### ISSUE TITLE
Gson failing to parse Shipment object

### ISSUE THREAD

**Issue by mharray** [EasyPost/easypost-java#54]
Hello, I'm getting an error in my production environment, that doesn't occur in my development environment. The relevant stacktrace is:

```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 129 path $.options.
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
at com.google.gson.Gson.fromJson(Gson.java:927)
at com.google.gson.Gson.fromJson(Gson.java:892)
at com.google.gson.Gson.fromJson(Gson.java:841)
at com.google.gson.Gson.fromJson(Gson.java:813)
at com.easypost.net.EasyPostResource._request(EasyPostResource.java:419)
at com.easypost.net.EasyPostResource.request(EasyPostResource.java:365)
at com.easypost.model.Shipment.create(Shipment.java:216)
at com.easypost.model.Shipment.create(Shipment.java:210)
at mp.server.hosting.EasyPostService.createShipment(EasyPostService.java:184)
```

The relevant JSON that it's failing to parse is:

```
"options":{
      "currency":"USD",
      "payment":{
         "type":"SENDER"
      },
      "date_advance":0
   }
```

It is trying to parse this into the `Map<String, Object> options;` field. However it appears to be expecting "payment" to be a String rather than a Json Object.

I have confirmed that the exact same JSON works in my development environment, but not my production environment. I'm not sure what's different about these two environments that would cause the inconsistency, other than my production environment is using OpenJDK. I am using the latest version of the easy post client, and have also tried using the latest version of Gson.

I think a Gson TypeAdapter for the Options object might be a good solution here to explicitly handle the mix of Objects and Strings in the `Map<String, Object> options;` field.

**Comment by Justintime50** [comment]
Hey @mharray, is this still an issue for you? Have you found any additional relevant information since initially submitting this PR?

**Comment by jchen293** [comment]
@mharray Are you still getting this issue with the latest version? We do like to investigate this issue, could you send us a snippet of Java code that arises from this exception?

**Comment by mharray** [comment]
> @mharray Are you still getting this issue with the latest version? We do like to investigate this issue, could you send us a snippet of Java code that arises from this exception?

I am no longer working on this project so am unable to provide any further information. Appreciate the support however
