### ISSUE TITLE
Seems like the error could be formatted better

### ISSUE THREAD

**Issue by mbeale** [EasyPost/easypost-java#6]
After failed address verificaton

Message within EasyPostException:

An error occured. Response code: 400 Response body: {"error":{"code":"ADDRESS.VERIFY.FAILURE","message":"Insufficient address data provided. A street must be provided.","errors":[]}}

**Comment by Justintime50** [comment]
Hey @mbeale this is an error returned by the API and not by the client library. As such, we'll probably close this issue as it's not something that can be addressed via this repo. @jontsai
