### ISSUE TITLE
Run tests in CI

### ISSUE THREAD

**Issue by Roguelazer** [EasyPost/easypost-java#62]
Our CI currently runs with `-DskipTests=true` because some of the tests don't work, and many of those that _do_ work aren't safe to run concurrently (which is required to test multiple versions of Java).

We should look into whether a good response mocking option a la vcr exists for whatever Java HTTP libraries we're using.

**Comment by Justintime50** [comment]
@nwithan8 once VCR is done, let's enable tests on CI and close this out.
