### ISSUE TITLE
API key looks static.  Does this sdk support multiple accounts?

### ISSUE THREAD

**Issue by perrytew** [EasyPost/easypost-java#64]
I'm looking at creating an integration between my e-commerce engine and your company.  That integration would support many merchants (different accounts) at one time.  Does your SDK have any means to handle that?  If not, is that something you would consider in your architecture?

**Comment by sawyer** [comment]
Hi Perry,

Yes, the API is stateless and the Java SDK handles this by optionally
accepting an API key as the final string argument to all of the methods.
For example, you could re-write the README sample:

...
// create shipment
Map<String, Object> shipmentMap = new HashMap<String, Object>();
shipmentMap.put("to_address", toAddress);
shipmentMap.put("from_address", fromAddress);
shipmentMap.put("parcel", parcel);
shipmentMap.put("customs_info", customsInfo);

Shipment shipment = Shipment.create(shipmentMap, "YOUR_API_KEY");
...

Your software would need to manage and store the customer's EasyPost API
key, but once you have that the SDK makes it very easy to statelessly
include an API key per request.

Cheers!

**Comment by perrytew** [comment]
Great news.  Thank you!
