### ISSUE TITLE
Address: Parameter missing when calling request() in createAndVerify()

### ISSUE THREAD

**Issue by rajsid1** [EasyPost/easypost-java#7]
[Address: createAndVerify()](https://github.com/EasyPost/easypost-java/blob/master/src/main/java/com/easypost/model/Address.java#L171) should pass param "wrappedParams" to [request()](https://github.com/EasyPost/easypost-java/blob/master/src/main/java/com/easypost/model/Address.java#L176) call.

**Comment by victoryftw** [comment]
It also needed to be a POST instead of a GET.

This is fixed in version 2.0.13.
