### ISSUE TITLE
Migration to eventually fix spelling error?

### ISSUE THREAD

**Issue by nwithan8** [EasyPost/easypost-java#78]
https://github.com/EasyPost/easypost-java/blob/cdd2d48333254a3a10200dace92b1fa6c0053d11/src/main/java/com/easypost/model/Tracker.java#L99

**Comment by jchen293** [comment]
It calls the method in the EasyPostResource file, but I think we can have a better naming for the method to avoid confusion.

**Comment by Justintime50** [comment]
Dang, should have included this in our last major version bump. Too bad. I'll file an internal task to accompany this so we can try to plan to include it whenever our next major version bump comes around.
