### ISSUE TITLE
IllegalStateException, GSON

### ISSUE THREAD

**Issue by rajsid1** [EasyPost/easypost-java#8]
`"java.lang.IllegalStateException: Expected a string but  was BEGIN_OBJECT at line 1 column 11"` at [line](https://github.com/EasyPost/easypost-java/blob/master/src/main/java/com/easypost/net/EasyPostResource.java#L423)

When JSON is `{"error":{"code":"ADDRESS.VERIFY.FAILURE","message":"Address Not Found. ","errors":[]}}`

**Comment by victoryftw** [comment]
I believe this was fixed in a previous version of this library. Can you confirm you are using the latest version and try again? Please reopen if it is still broken.
